---
abstract: 'Scalar variables that time out'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tie-Scalar-Timeout
provides:
  Tie::Scalar::Timeout:
    file: lib/Tie/Scalar/Timeout.pm
    version: 1.100880
requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.88
  Tie::Scalar: 0
  Time::Local: 0
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Tie-Scalar-Timeout
  homepage: http://search.cpan.org/dist/Tie-Scalar-Timeout/
  repository: http://github.com/hanekomu/Tie-Scalar-Timeout
version: 1.100880
